api-module: b

base:
  api:
    prefix: api
  server:
    # 是否启用，默认：true
    enable: true
    # 端口号
    port: 18011
    # web框架gin的配置
    gin:
      # 有三种模式：debug/release/test，填错则使用release
      mode: debug
  redis:
    enable: true
    standalone:
      addr: localhost:16379

biz:
  url:
    a: http://localhost:18010
    c: http://localhost:18012
    d: http://localhost:18013
    e: http://localhost:18014
