api-module: b

base:
  api:
    prefix: api
  server:
    # 是否启用，默认：true
    enable: true
    # 端口号
    port: 18001
    # web框架gin的配置
    gin:
      # 有三种模式：debug/release/test，填错则使用release
      mode: release
    response:
      print:
        # 是否打印：true, false；默认 false
        enable: true
  redis:
    enable: true
    standalone:
      addr: redis-service:6379

  endpoint:
    # 配置的管理（查看和变更），默认关闭，true/false
    config:
      enable: true

biz:
  url:
    a: http://localhost:18000
#    a: http://biz-a-service:18000
    c: http://localhost:18002
#    c: http://biz-c-service:18002
    d: http://localhost:18003
#    d: http://biz-d-service:18003
    e: http://localhost:18004
#    e: http://biz-e-service:18004
